[package]
name = "type-carnival"
version = "0.1.0"
authors = ["monymoney <mopro0414@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
rand = "0.7.3"
nom = "5.1.2"
device_query = "0.2.4"